
export const quotes = [
  "The sun will shine on us again.",
  "Everything is awesome!",
  "It’s not who I am underneath, but what I do that defines me.",
  "Just keep swimming.",
  "The way I see it, if you want the rainbow, you gotta put up with the rain.",
  "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
  "Do or do not. There is no try.",
  "I can do this all day.",
  "Your focus determines your reality.",
  "To infinity and beyond!",
  "The only way to achieve the impossible is to believe it is possible.",
  "The problem is not the problem. The problem is your attitude about the problem.",
  "Great men are not born great, they grow great.",
  "Whatever you are, be a good one.",
  "The best way to predict the future is to create it.",
  "Every strike brings me closer to the next home run.",
  "Believe you can and you're halfway there.",
  "Act as if what you do makes a difference. It does.",
  "No matter what people tell you, words and ideas can change the world.",
  "Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Our lives are defined by opportunities, even the ones we miss.",
  "Don't let anyone ever make you feel like you don't deserve what you want.",
  "Why do we fall, sir? So that we can learn to pick ourselves up.",
  "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.",
  "Even the smallest person can change the course of the future.",
  "You must be the change you wish to see in the world.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "The only true wisdom is in knowing you know nothing.",
  "The journey of a thousand miles begins with one step.",
  "Dream as if you'll live forever. Live as if you'll die today.",
  "Stay hungry, stay foolish.",
  "In the middle of every difficulty lies opportunity.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Sometimes the right path is not the easiest one.",
  "It is our choices that show what we truly are, far more than our abilities.",
  "Courage is being scared to death, but saddling up anyway.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Do what you can, with what you have, where you are.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Don't count the days, make the days count.",
  "A hero can be anyone.",
  "I’m a big fan of ignoreland. When you can’t change it, ignore it.",
  "If you’re going through hell, keep going.",
  "You miss 100% of the shots you don't take.",
  "The mind is everything. What you think you become.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "Positive anything is better than negative nothing.",
  "The power of imagination makes us infinite.",
  "The only thing we have to fear is fear itself.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "With great power comes great responsibility.",
  "The flower that blooms in adversity is the most rare and beautiful of all.",
  "It's just a flesh wound.",
  "I am Groot.",
  "There’s no place like home.",
  "May the Force be with you.",
  "I'm the king of the world!",
  "Carpe diem. Seize the day, boys. Make your lives extraordinary.",
  "What we do in life echoes in eternity.",
  "It’s a-me, Mario!",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The way to get started is to quit talking and begin doing.",
  "Your time is limited, so don't waste it living someone else's life.",
  "If life were predictable it would cease to be life, and be without flavor.",
  "If you look at what you have in life, you'll always have more.",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
  "Life is what happens when you're busy making other plans.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "The purpose of our lives is to be happy.",
  "Life is a succession of lessons which must be lived to be understood.",
  "You only live once, but if you do it right, once is enough.",
  "Live in the sunshine, swim the sea, drink the wild air.",
  "Go confidently in the direction of your dreams! Live the life you've imagined.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "It is never too late to be what you might have been.",
  "Everything has beauty, but not everyone can see.",
  "The most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "Strive not to be a success, but rather to be of value.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "The only source of knowledge is experience.",
  "What is important is to keep learning, to enjoy challenge, and to tolerate ambiguity. In the end there are no certain answers.",
  "A person who never made a mistake never tried anything new.",
  "Try not to become a man of success. Rather become a man of value.",
  "The true sign of intelligence is not knowledge but imagination.",
  "We cannot solve our problems with the same thinking we used when we created them.",
  "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.",
  "Anyone who has never made a mistake has never tried anything new.",
  "I have no special talent. I am only passionately curious.",
  "Look deep into nature, and then you will understand everything better.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "No amount of experimentation can ever prove me right; a single experiment can prove me wrong.",
  "Only a life lived for others is a life worthwhile.",
  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.",
  "There are two ways to live: you can live as if nothing is a miracle; you can live as if everything is a miracle.",
  "Peace cannot be kept by force; it can only be achieved by understanding.",
  "Imagination is everything. It is the preview of life's coming attractions.",
  "The important thing is not to stop questioning. Curiosity has its own reason for existing.",
  "Science without religion is lame, religion without science is blind.",
  "Gravity is not responsible for people falling in love.",
  "The measure of intelligence is the ability to change.",
  "Reality is merely an illusion, albeit a very persistent one.",
  "It is the supreme art of the teacher to awaken joy in creative expression and knowledge.",
  "Once we accept our limits, we go beyond them.",
  "Genius is 1% talent and 99% percent hard work.",
  "Black holes are where God divided by zero.",
  "If you can't explain it simply, you don't understand it well enough.",
  "The most incomprehensible thing about the world is that it is comprehensible.",
  "I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.",
  "You never fail until you stop trying.",
  "Weakness of attitude becomes weakness of character.",
  "A clever person solves a problem. A wise person avoids it.",
  "Logic will get you from A to B. Imagination will take you everywhere.",
  "The world is a dangerous place to live, not because of the people who are evil, but because of the people who don't do anything about it.",
  "When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.",
  "If A is a success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your mouth shut.",
  "All that is gold does not glitter, not all those who wander are lost.",
  "The secret of getting ahead is getting started.",
  "It's not the years in your life that count. It's the life in your years.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "The future is not something we enter. The future is something we create.",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "The only impossible journey is the one you never begin.",
  "In this life we cannot do great things. We can only do small things with great love.",
  "You are never too old to set another goal or to dream a new dream.",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
  "What we think, we become.",
  "May your choices reflect your hopes, not your fears.",
  "There is no greater agony than bearing an untold story inside you.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "The greatest wealth is to live content with little.",
  "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.",
  "It is not death that a man should fear, but he should fear never beginning to live.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "There is no charm equal to tenderness of heart.",
  "The only person you are destined to become is the person you decide to be.",
  "Go forth and set the world on fire.",
  "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
  "When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.",
  "The happiness of your life depends upon the quality of your thoughts.",
  "Waste no more time arguing about what a good man should be. Be one.",
  "It’s not what happens to you, but how you react to it that matters.",
  "The best revenge is to be unlike him who performed the injury.",
  "The soul becomes dyed with the colour of its thoughts.",
  "He who lives in harmony with himself lives in harmony with the universe.",
  "You have power over your mind - not outside events. Realize this, and you will find strength.",
  "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.",
  "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
  "The first rule of Fight Club is: You do not talk about Fight Club.",
  "I'm going to make him an offer he can't refuse.",
  "Houston, we have a problem.",
  "You're gonna need a bigger boat.",
  "I'll be back.",
  "Go ahead, make my day.",
  "Nobody puts Baby in a corner.",
  "I am serious. And don't call me Shirley.",
  "Here's looking at you, kid.",
  "I feel the need—the need for speed!",
  "The stuff that dreams are made of.",
  "E.T. phone home.",
  "You can't handle the truth!",
  "A martini. Shaken, not stirred.",
  "This is the beginning of a beautiful friendship.",
  "I see dead people.",
  "Bond. James Bond.",
  "Elementary, my dear Watson.",
  "That'll do, pig. That'll do.",
  "Chewie, we’re home.",
  "I'm having an old friend for dinner.",
  "Roads? Where we're going we don't need roads.",
  "Say 'hello' to my little friend!",
  "What's in the box?",
  "I am your father.",
  "Why so serious?",
  "Some people can’t believe in themselves until someone else believes in them first.",
  "It is not our abilities that show what we truly are… it is our choices.",
  "All we have to decide is what to do with the time that is given us.",
  "Your time as a caterpillar has expired. Your wings are ready.",
  "The very things that hold you down are going to lift you up.",
  "The past is just a story we tell ourselves.",
  "You are the hero of your own story.",
  "A little consideration, a little thought for others, makes all the difference.",
  "The moment you doubt whether you can fly, you cease for ever to be able to do it.",
  "You're mad. Bonkers. Off your head. But I'll tell you a secret: all the best people are.",
  "The world is not in your books and maps, it’s out there.",
  "Adventure is out there!",
  "There is a great deal of difference between an eager man who wants to read a book and a tired man who wants a book to read.",
  "Today is a good day to try.",
  "I shall not waste my days in trying to prolong them. I shall use my time.",
  "You are not a drop in the ocean. You are the entire ocean in a drop.",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
  "Raise your words, not your voice. It is rain that grows flowers, not thunder.",
  "The wound is the place where the Light enters you.",
  "What you seek is seeking you.",
  "Don't grieve. Anything you lose comes round in another form.",
  "Stop acting so small. You are the universe in ecstatic motion.",
  "The quieter you become, the more you are able to hear.",
  "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.",
  "The only lasting beauty is the beauty of the heart.",
  "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.",
  "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.",
  "When you do things from your soul, you feel a river moving in you, a joy.",
  "The world is full of magical things patiently waiting for our wits to grow sharper.",
  "Our job is to love others without stopping to inquire whether or not they are worthy.",
  "The desire to know your own soul will end all other desires.",
  "Where there is ruin, there is hope for a treasure.",
  "Be like a tree and let the dead leaves drop.",
  "The art of knowing is knowing what to ignore.",
  "If you are irritated by every rub, how will your mirror be polished?",
  "Two there are who are never satisfied -- the lover of the world and the lover of knowledge.",
  "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.",
  "Sell your cleverness and buy bewilderment.",
  "Respond to every call that excites your spirit.",
  "Let the beauty we love be what we do.",
  "Set your life on fire. Seek those who fan your flames.",
  "Your heart knows the way. Run in that direction.",
  "Be empty of worrying. Think of who created thought.",
  "The moon stays bright when it doesn't avoid the night.",
  "It's your road, and yours alone. Others may walk it with you, but no one can walk it for you.",
  "I am not this hair, I am not this skin, I am the soul that lives within.",
  "To be happy is a choice. You can choose to be happy. There's going to be stress in life, but it's your choice whether you let it affect you or not.",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
  "Optimism is the one quality more associated with success and happiness than any other.",
  "Your positive action combined with positive thinking results in success.",
  "The more you are in a state of gratitude, the more you will attract things to be grateful for.",
  "What you have done is nothing compared to what you can do.",
  "The most important thing is to enjoy your life - to be happy - it's all that matters.",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
  "I am thankful for all of those who said NO to me. It’s because of them I’m doing it myself.",
  "Today’s special moments are tomorrow’s memories.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "The only way to do great work is to love what you do.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "You can, you should, and if you’re brave enough to start, you will.",
  "The successful warrior is the average man, with laser-like focus.",
  "Don't be afraid to give up the good to go for the great.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "All our dreams can come true, if we have the courage to pursue them.",
  "If you do what you’ve always done, you’ll get what you’ve always gotten.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Opportunities don't happen. You create them.",
  "I find that the harder I work, the more luck I seem to have.",
  "The road to success and the road to failure are almost exactly the same.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be distracted by criticism. Remember -- the only taste of success some people get is to take a bite out of you.",
  "I never dreamed about success. I worked for it.",
  "There is no substitute for hard work.",
  "What seems to us as bitter trials are often blessings in disguise.",
  "The distance between insanity and genius is measured only by success.",
  "I cannot give you the formula for success, but I can give you the formula for failure--It is: Try to please everybody.",
  "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere.",
  "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "To succeed in life, you need two things: ignorance and confidence.",
  "I'm a success today because I had a friend who believed in me and I didn't have the heart to let him down.",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
  "Things work out best for those who make the best of how things work out.",
  "Try not to become a person of success, but rather try to become a person of value.",
  "Never give in except to convictions of honor and good sense.",
  "Stop chasing the money and start chasing the passion.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!",
  "The number one reason people fail in life is because they listen to their friends, family, and neighbors.",
  "You know you are on the road to success if you would do your job, and not be paid for it.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
  "Fall seven times and stand up eight.",
  "Some people dream of success while others wake up and work hard at it.",
  "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.",
  "If you aren't going all the way, why go at all?",
  "The question isn’t who is going to let me; it’s who is going to stop me.",
  "The only place where success comes before work is in the dictionary.",
  "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down.",
  "I will not let anyone walk through my mind with their dirty feet.",
  "We are still masters of our fate. We are still captains of our souls.",
  "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.",
  "Be yourself; everyone else is already taken.",
  "I'm so clever that sometimes I don't understand a single word of what I am saying.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "True friends stab you in the front.",
  "Always forgive your enemies; nothing annoys them so much.",
  "The truth is rarely pure and never simple.",
  "A good friend will always stab you in the front.",
  "I have the simplest of tastes. I am always satisfied with the best.",
  "To love oneself is the beginning of a lifelong romance.",
  "Be yourself, but be your best self.",
  "You can never be overdressed or overeducated.",
  "A man who does not think for himself does not think at all.",
  "Life is not a problem to be solved, but a reality to be experienced.",
  "The purpose of life is to be defeated by greater and greater things.",
  "There is nothing permanent except change.",
  "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.",
  "Change your thoughts and you change your world.",
  "It is not in the stars to hold our destiny but in ourselves.",
  "A journey of a thousand miles must begin with a single step.",
  "I have not failed. I have just found 10,000 ways that won’t work.",
  "It does not matter how slowly you go as long as you do not stop.",
  "I hear and I forget. I see and I remember. I do and I understand.",
  "Choose a job you love, and you will never have to work a day in your life.",
  "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "The more man meditates upon good thoughts, the better will be his world and the world at large.",
  "Wheresoever you go, go with all your heart.",
  "I want to know God's thoughts... the rest are details.",
  "Everything that is really great and inspiring is created by the individual who can labor in freedom.",
  "Don't worry about your difficulties in Mathematics. I can assure you mine are still greater.",
  "Imagination is more important than knowledge.",
  "We still do not know one thousandth of one percent of what nature has revealed to us.",
  "One of the strongest characteristics of genius is the power of lighting its own fire.",
  "The beginning is the most important part of the work.",
  "An ounce of prevention is worth a pound of cure.",
  "All you need is love. But a little chocolate now and then doesn't hurt.",
  "For every minute you are angry you lose sixty seconds of happiness.",
  "It's no use going back to yesterday, because I was a different person then.",
  "If you don't know where you are going, any road will get you there.",
  "Would you tell me, please, which way I ought to go from here? 'That depends a good deal on where you want to get to,' said the Cat.",
];
